#!/usr/bin/env bash
source "$(dirname "$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)")/config"
set -eo pipefail
[[ $DOKKU_TRACE ]] && set -x
source "$PLUGIN_BASE_PATH/common/functions"
source "$(dirname "$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)")/functions"

service-login-cmd() {
  declare desc="login to the db server running in a $PLUGIN_SERVICE service container"
  local cmd="$PLUGIN_COMMAND_PREFIX:login" argv=("$@")
  [[ ${argv[0]} == "$cmd" ]] && shift 1
  declare SERVICE="$1"

  verify_service_name "$SERVICE"
  dokku_log_info1_quiet "Filesystem changes may not persist after container restarts"
  service_login "$SERVICE"
}

service-login-cmd "$@"
